services:
  frontend:
    container_name: frontend
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/usr/code
    ports:
      - 4200:4200
    expose:
      - 4200
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: frontendblog
      SERVER_PORT: 4200
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge